#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 130
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 60
#define ALIAS_COUNT 1
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define PRODUCTION_ID_COUNT 2

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_alias = 2,
  anon_sym_EQ = 3,
  sym_ident = 4,
  anon_sym_LBRACK = 5,
  anon_sym_RBRACK = 6,
  anon_sym_fn = 7,
  anon_sym_LPAREN = 8,
  anon_sym_RPAREN = 9,
  anon_sym_COLON = 10,
  anon_sym_extern = 11,
  anon_sym_type = 12,
  anon_sym_LBRACE = 13,
  anon_sym_COMMA = 14,
  anon_sym_RBRACE = 15,
  anon_sym_let = 16,
  anon_sym_if = 17,
  anon_sym_else = 18,
  anon_sym_PLUS = 19,
  anon_sym_STAR = 20,
  anon_sym_SLASH = 21,
  anon_sym_DASH = 22,
  anon_sym_PIPE_PIPE = 23,
  anon_sym_AMP_AMP = 24,
  anon_sym_LT = 25,
  anon_sym_GT = 26,
  anon_sym_GT_EQ = 27,
  anon_sym_LT_EQ = 28,
  sym_string = 29,
  anon_sym_true = 30,
  anon_sym_false = 31,
  sym_number = 32,
  sym_source_file = 33,
  sym_definition = 34,
  sym_type_def = 35,
  sym_alias = 36,
  sym_type = 37,
  sym_array_type = 38,
  sym_fn_type = 39,
  sym_extern_def = 40,
  sym_struct_def = 41,
  sym_annotated_ident = 42,
  sym_enum_def = 43,
  sym_let = 44,
  sym_expr = 45,
  sym_functioncall = 46,
  sym_ifelse = 47,
  sym_binary_op = 48,
  sym_literal = 49,
  sym_array = 50,
  sym_bool = 51,
  sym_function = 52,
  sym_block = 53,
  aux_sym_source_file_repeat1 = 54,
  aux_sym_fn_type_repeat1 = 55,
  aux_sym_struct_def_repeat1 = 56,
  aux_sym_enum_def_repeat1 = 57,
  aux_sym_functioncall_repeat1 = 58,
  aux_sym_block_repeat1 = 59,
  alias_sym_typename = 60,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_alias] = "alias",
  [anon_sym_EQ] = "=",
  [sym_ident] = "ident",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_fn] = "fn",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_extern] = "extern",
  [anon_sym_type] = "type",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_let] = "let",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_PLUS] = "+",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_DASH] = "-",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_EQ] = "<=",
  [sym_string] = "string",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_number] = "number",
  [sym_source_file] = "source_file",
  [sym_definition] = "definition",
  [sym_type_def] = "type_def",
  [sym_alias] = "alias",
  [sym_type] = "type",
  [sym_array_type] = "array_type",
  [sym_fn_type] = "fn_type",
  [sym_extern_def] = "extern_def",
  [sym_struct_def] = "struct_def",
  [sym_annotated_ident] = "annotated_ident",
  [sym_enum_def] = "enum_def",
  [sym_let] = "let",
  [sym_expr] = "expr",
  [sym_functioncall] = "functioncall",
  [sym_ifelse] = "ifelse",
  [sym_binary_op] = "binary_op",
  [sym_literal] = "literal",
  [sym_array] = "array",
  [sym_bool] = "bool",
  [sym_function] = "function",
  [sym_block] = "block",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_fn_type_repeat1] = "fn_type_repeat1",
  [aux_sym_struct_def_repeat1] = "struct_def_repeat1",
  [aux_sym_enum_def_repeat1] = "enum_def_repeat1",
  [aux_sym_functioncall_repeat1] = "functioncall_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [alias_sym_typename] = "typename",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_alias] = anon_sym_alias,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_ident] = sym_ident,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_extern] = anon_sym_extern,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [sym_string] = sym_string,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_number] = sym_number,
  [sym_source_file] = sym_source_file,
  [sym_definition] = sym_definition,
  [sym_type_def] = sym_type_def,
  [sym_alias] = sym_alias,
  [sym_type] = sym_type,
  [sym_array_type] = sym_array_type,
  [sym_fn_type] = sym_fn_type,
  [sym_extern_def] = sym_extern_def,
  [sym_struct_def] = sym_struct_def,
  [sym_annotated_ident] = sym_annotated_ident,
  [sym_enum_def] = sym_enum_def,
  [sym_let] = sym_let,
  [sym_expr] = sym_expr,
  [sym_functioncall] = sym_functioncall,
  [sym_ifelse] = sym_ifelse,
  [sym_binary_op] = sym_binary_op,
  [sym_literal] = sym_literal,
  [sym_array] = sym_array,
  [sym_bool] = sym_bool,
  [sym_function] = sym_function,
  [sym_block] = sym_block,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_fn_type_repeat1] = aux_sym_fn_type_repeat1,
  [aux_sym_struct_def_repeat1] = aux_sym_struct_def_repeat1,
  [aux_sym_enum_def_repeat1] = aux_sym_enum_def_repeat1,
  [aux_sym_functioncall_repeat1] = aux_sym_functioncall_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [alias_sym_typename] = alias_sym_typename,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_alias] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extern] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_type_def] = {
    .visible = true,
    .named = true,
  },
  [sym_alias] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_array_type] = {
    .visible = true,
    .named = true,
  },
  [sym_fn_type] = {
    .visible = true,
    .named = true,
  },
  [sym_extern_def] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_def] = {
    .visible = true,
    .named = true,
  },
  [sym_annotated_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_def] = {
    .visible = true,
    .named = true,
  },
  [sym_let] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_functioncall] = {
    .visible = true,
    .named = true,
  },
  [sym_ifelse] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_op] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fn_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_def_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_def_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_functioncall_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_typename] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_typename,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(31);
      ADVANCE_MAP(
        '"', 30,
        '&', 3,
        '(', 51,
        ')', 52,
        '*', 65,
        '+', 64,
        ',', 57,
        '-', 67,
        '/', 66,
        ':', 53,
        ';', 32,
        '<', 70,
        '=', 34,
        '>', 71,
        '[', 47,
        ']', 48,
        'a', 16,
        'e', 17,
        'f', 6,
        'i', 14,
        'l', 13,
        't', 21,
        '{', 56,
        '|', 29,
        '}', 58,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 30,
        ')', 52,
        '[', 47,
        ']', 48,
        'f', 35,
        'i', 39,
        'l', 36,
        't', 42,
        '}', 58,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '&') ADVANCE(69);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        ')', 52,
        ',', 57,
        ';', 32,
        '[', 47,
        ']', 48,
        'f', 41,
        '{', 56,
        '}', 58,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 5:
      if (lookahead == ')') ADVANCE(52);
      if (lookahead == ']') ADVANCE(48);
      if (lookahead == '}') ADVANCE(58);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(18);
      if (lookahead == 'n') ADVANCE(49);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(23);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(63);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(75);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(55);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(77);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 14:
      if (lookahead == 'f') ADVANCE(61);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(7);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(15);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(24);
      if (lookahead == 'x') ADVANCE(27);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(54);
      END_STATE();
    case 20:
      if (lookahead == 'p') ADVANCE(11);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(28);
      if (lookahead == 'y') ADVANCE(20);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 23:
      if (lookahead == 's') ADVANCE(33);
      END_STATE();
    case 24:
      if (lookahead == 's') ADVANCE(8);
      END_STATE();
    case 25:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(59);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(9);
      END_STATE();
    case 28:
      if (lookahead == 'u') ADVANCE(10);
      END_STATE();
    case 29:
      if (lookahead == '|') ADVANCE(68);
      END_STATE();
    case 30:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_alias);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'a') ADVANCE(40);
      if (lookahead == 'n') ADVANCE(50);
      if (lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(44);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(76);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(78);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'f') ADVANCE(62);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'l') ADVANCE(43);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'n') ADVANCE(50);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'r') ADVANCE(45);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 's') ADVANCE(38);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 't') ADVANCE(60);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'u') ADVANCE(37);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_fn);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_extern);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_let);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_if);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(73);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(72);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 4},
  [49] = {.lex_state = 4},
  [50] = {.lex_state = 4},
  [51] = {.lex_state = 4},
  [52] = {.lex_state = 4},
  [53] = {.lex_state = 4},
  [54] = {.lex_state = 4},
  [55] = {.lex_state = 4},
  [56] = {.lex_state = 4},
  [57] = {.lex_state = 4},
  [58] = {.lex_state = 4},
  [59] = {.lex_state = 4},
  [60] = {.lex_state = 4},
  [61] = {.lex_state = 4},
  [62] = {.lex_state = 4},
  [63] = {.lex_state = 4},
  [64] = {.lex_state = 4},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 5},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 5},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 5},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 5},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 5},
  [90] = {.lex_state = 5},
  [91] = {.lex_state = 5},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 5},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 5},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 5},
  [109] = {.lex_state = 5},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 5},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 5},
  [127] = {.lex_state = 5},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 5},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_alias] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_extern] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(125),
    [sym_definition] = STATE(124),
    [sym_type_def] = STATE(122),
    [sym_alias] = STATE(120),
    [sym_extern_def] = STATE(122),
    [sym_struct_def] = STATE(120),
    [sym_enum_def] = STATE(120),
    [sym_let] = STATE(122),
    [aux_sym_source_file_repeat1] = STATE(44),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_alias] = ACTIONS(5),
    [anon_sym_extern] = ACTIONS(7),
    [anon_sym_type] = ACTIONS(9),
    [anon_sym_let] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(13), 1,
      sym_ident,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_RPAREN,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_if,
    STATE(45), 1,
      sym_expr,
    ACTIONS(25), 2,
      sym_string,
      sym_number,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(32), 3,
      sym_array,
      sym_bool,
      sym_function,
    STATE(34), 5,
      sym_let,
      sym_functioncall,
      sym_ifelse,
      sym_binary_op,
      sym_literal,
  [42] = 11,
    ACTIONS(13), 1,
      sym_ident,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(29), 1,
      anon_sym_RBRACK,
    STATE(41), 1,
      sym_expr,
    ACTIONS(25), 2,
      sym_string,
      sym_number,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(32), 3,
      sym_array,
      sym_bool,
      sym_function,
    STATE(34), 5,
      sym_let,
      sym_functioncall,
      sym_ifelse,
      sym_binary_op,
      sym_literal,
  [84] = 11,
    ACTIONS(13), 1,
      sym_ident,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(31), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      sym_expr,
    ACTIONS(25), 2,
      sym_string,
      sym_number,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(32), 3,
      sym_array,
      sym_bool,
      sym_function,
    STATE(34), 5,
      sym_let,
      sym_functioncall,
      sym_ifelse,
      sym_binary_op,
      sym_literal,
  [126] = 11,
    ACTIONS(13), 1,
      sym_ident,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_RBRACK,
    STATE(43), 1,
      sym_expr,
    ACTIONS(25), 2,
      sym_string,
      sym_number,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(32), 3,
      sym_array,
      sym_bool,
      sym_function,
    STATE(34), 5,
      sym_let,
      sym_functioncall,
      sym_ifelse,
      sym_binary_op,
      sym_literal,
  [168] = 11,
    ACTIONS(13), 1,
      sym_ident,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(35), 1,
      anon_sym_RBRACE,
    STATE(47), 1,
      sym_expr,
    ACTIONS(25), 2,
      sym_string,
      sym_number,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(32), 3,
      sym_array,
      sym_bool,
      sym_function,
    STATE(34), 5,
      sym_let,
      sym_functioncall,
      sym_ifelse,
      sym_binary_op,
      sym_literal,
  [210] = 11,
    ACTIONS(13), 1,
      sym_ident,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(37), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      sym_expr,
    ACTIONS(25), 2,
      sym_string,
      sym_number,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(32), 3,
      sym_array,
      sym_bool,
      sym_function,
    STATE(34), 5,
      sym_let,
      sym_functioncall,
      sym_ifelse,
      sym_binary_op,
      sym_literal,
  [252] = 11,
    ACTIONS(13), 1,
      sym_ident,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(39), 1,
      anon_sym_RBRACE,
    STATE(47), 1,
      sym_expr,
    ACTIONS(25), 2,
      sym_string,
      sym_number,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(32), 3,
      sym_array,
      sym_bool,
      sym_function,
    STATE(34), 5,
      sym_let,
      sym_functioncall,
      sym_ifelse,
      sym_binary_op,
      sym_literal,
  [294] = 11,
    ACTIONS(13), 1,
      sym_ident,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(41), 1,
      anon_sym_RBRACK,
    STATE(43), 1,
      sym_expr,
    ACTIONS(25), 2,
      sym_string,
      sym_number,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(32), 3,
      sym_array,
      sym_bool,
      sym_function,
    STATE(34), 5,
      sym_let,
      sym_functioncall,
      sym_ifelse,
      sym_binary_op,
      sym_literal,
  [336] = 10,
    ACTIONS(13), 1,
      sym_ident,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_if,
    STATE(27), 1,
      sym_expr,
    ACTIONS(25), 2,
      sym_string,
      sym_number,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(32), 3,
      sym_array,
      sym_bool,
      sym_function,
    STATE(34), 5,
      sym_let,
      sym_functioncall,
      sym_ifelse,
      sym_binary_op,
      sym_literal,
  [375] = 10,
    ACTIONS(13), 1,
      sym_ident,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_if,
    STATE(35), 1,
      sym_expr,
    ACTIONS(25), 2,
      sym_string,
      sym_number,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(32), 3,
      sym_array,
      sym_bool,
      sym_function,
    STATE(34), 5,
      sym_let,
      sym_functioncall,
      sym_ifelse,
      sym_binary_op,
      sym_literal,
  [414] = 10,
    ACTIONS(13), 1,
      sym_ident,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_if,
    STATE(42), 1,
      sym_expr,
    ACTIONS(25), 2,
      sym_string,
      sym_number,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(32), 3,
      sym_array,
      sym_bool,
      sym_function,
    STATE(34), 5,
      sym_let,
      sym_functioncall,
      sym_ifelse,
      sym_binary_op,
      sym_literal,
  [453] = 10,
    ACTIONS(13), 1,
      sym_ident,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_if,
    STATE(46), 1,
      sym_expr,
    ACTIONS(25), 2,
      sym_string,
      sym_number,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(32), 3,
      sym_array,
      sym_bool,
      sym_function,
    STATE(34), 5,
      sym_let,
      sym_functioncall,
      sym_ifelse,
      sym_binary_op,
      sym_literal,
  [492] = 10,
    ACTIONS(13), 1,
      sym_ident,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_if,
    STATE(47), 1,
      sym_expr,
    ACTIONS(25), 2,
      sym_string,
      sym_number,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(32), 3,
      sym_array,
      sym_bool,
      sym_function,
    STATE(34), 5,
      sym_let,
      sym_functioncall,
      sym_ifelse,
      sym_binary_op,
      sym_literal,
  [531] = 10,
    ACTIONS(13), 1,
      sym_ident,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_if,
    STATE(43), 1,
      sym_expr,
    ACTIONS(25), 2,
      sym_string,
      sym_number,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(32), 3,
      sym_array,
      sym_bool,
      sym_function,
    STATE(34), 5,
      sym_let,
      sym_functioncall,
      sym_ifelse,
      sym_binary_op,
      sym_literal,
  [570] = 2,
    ACTIONS(45), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(43), 15,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_else,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [592] = 2,
    ACTIONS(49), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(47), 15,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_else,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [614] = 2,
    ACTIONS(53), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(51), 15,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_else,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [636] = 3,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(55), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [660] = 2,
    ACTIONS(63), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(61), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [681] = 2,
    ACTIONS(67), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(65), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [702] = 2,
    ACTIONS(71), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(69), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [723] = 2,
    ACTIONS(75), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(73), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [744] = 2,
    ACTIONS(79), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(77), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [765] = 2,
    ACTIONS(83), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(81), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [786] = 2,
    ACTIONS(87), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(85), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [807] = 2,
    ACTIONS(91), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(89), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [828] = 2,
    ACTIONS(95), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(93), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [849] = 2,
    ACTIONS(99), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(97), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [870] = 2,
    ACTIONS(103), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(101), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [891] = 2,
    ACTIONS(107), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(105), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [912] = 2,
    ACTIONS(111), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(109), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [933] = 2,
    ACTIONS(115), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(113), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [954] = 2,
    ACTIONS(59), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(55), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [975] = 3,
    ACTIONS(121), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(117), 6,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
    ACTIONS(119), 8,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [998] = 2,
    ACTIONS(125), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(123), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1019] = 2,
    ACTIONS(129), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(127), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1040] = 2,
    ACTIONS(133), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(131), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1061] = 2,
    ACTIONS(137), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(135), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1082] = 9,
    ACTIONS(139), 1,
      ts_builtin_sym_end,
    ACTIONS(141), 1,
      anon_sym_alias,
    ACTIONS(144), 1,
      anon_sym_extern,
    ACTIONS(147), 1,
      anon_sym_type,
    ACTIONS(150), 1,
      anon_sym_let,
    STATE(40), 1,
      aux_sym_source_file_repeat1,
    STATE(124), 1,
      sym_definition,
    STATE(120), 3,
      sym_alias,
      sym_struct_def,
      sym_enum_def,
    STATE(122), 3,
      sym_type_def,
      sym_extern_def,
      sym_let,
  [1114] = 5,
    ACTIONS(153), 1,
      anon_sym_RBRACK,
    ACTIONS(155), 1,
      anon_sym_COMMA,
    STATE(82), 1,
      aux_sym_functioncall_repeat1,
    ACTIONS(121), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(119), 8,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1138] = 5,
    ACTIONS(157), 1,
      anon_sym_SEMI,
    ACTIONS(159), 1,
      anon_sym_RBRACE,
    STATE(72), 1,
      aux_sym_block_repeat1,
    ACTIONS(121), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(119), 8,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1162] = 3,
    ACTIONS(121), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(161), 3,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(119), 8,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1182] = 9,
    ACTIONS(5), 1,
      anon_sym_alias,
    ACTIONS(7), 1,
      anon_sym_extern,
    ACTIONS(9), 1,
      anon_sym_type,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(163), 1,
      ts_builtin_sym_end,
    STATE(40), 1,
      aux_sym_source_file_repeat1,
    STATE(124), 1,
      sym_definition,
    STATE(120), 3,
      sym_alias,
      sym_struct_def,
      sym_enum_def,
    STATE(122), 3,
      sym_type_def,
      sym_extern_def,
      sym_let,
  [1214] = 5,
    ACTIONS(165), 1,
      anon_sym_RPAREN,
    ACTIONS(167), 1,
      anon_sym_COMMA,
    STATE(81), 1,
      aux_sym_functioncall_repeat1,
    ACTIONS(121), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(119), 8,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1238] = 4,
    ACTIONS(169), 1,
      anon_sym_LBRACE,
    STATE(107), 1,
      sym_block,
    ACTIONS(121), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(119), 8,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1259] = 3,
    ACTIONS(121), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(171), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(119), 8,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1278] = 2,
    ACTIONS(175), 2,
      sym_ident,
      anon_sym_fn,
    ACTIONS(173), 7,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1292] = 2,
    ACTIONS(179), 2,
      sym_ident,
      anon_sym_fn,
    ACTIONS(177), 7,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1306] = 2,
    ACTIONS(183), 2,
      sym_ident,
      anon_sym_fn,
    ACTIONS(181), 7,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1320] = 2,
    ACTIONS(187), 2,
      sym_ident,
      anon_sym_fn,
    ACTIONS(185), 7,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1334] = 6,
    ACTIONS(189), 1,
      sym_ident,
    ACTIONS(191), 1,
      anon_sym_LBRACK,
    ACTIONS(193), 1,
      anon_sym_fn,
    ACTIONS(195), 1,
      anon_sym_RPAREN,
    STATE(50), 2,
      sym_array_type,
      sym_fn_type,
    STATE(53), 2,
      sym_type,
      aux_sym_fn_type_repeat1,
  [1355] = 6,
    ACTIONS(189), 1,
      sym_ident,
    ACTIONS(191), 1,
      anon_sym_LBRACK,
    ACTIONS(193), 1,
      anon_sym_fn,
    ACTIONS(197), 1,
      anon_sym_RPAREN,
    STATE(50), 2,
      sym_array_type,
      sym_fn_type,
    STATE(54), 2,
      sym_type,
      aux_sym_fn_type_repeat1,
  [1376] = 6,
    ACTIONS(199), 1,
      sym_ident,
    ACTIONS(202), 1,
      anon_sym_LBRACK,
    ACTIONS(205), 1,
      anon_sym_fn,
    ACTIONS(208), 1,
      anon_sym_RPAREN,
    STATE(50), 2,
      sym_array_type,
      sym_fn_type,
    STATE(54), 2,
      sym_type,
      aux_sym_fn_type_repeat1,
  [1397] = 5,
    ACTIONS(189), 1,
      sym_ident,
    ACTIONS(191), 1,
      anon_sym_LBRACK,
    ACTIONS(193), 1,
      anon_sym_fn,
    STATE(111), 1,
      sym_type,
    STATE(50), 2,
      sym_array_type,
      sym_fn_type,
  [1414] = 5,
    ACTIONS(189), 1,
      sym_ident,
    ACTIONS(191), 1,
      anon_sym_LBRACK,
    ACTIONS(193), 1,
      anon_sym_fn,
    STATE(74), 1,
      sym_type,
    STATE(50), 2,
      sym_array_type,
      sym_fn_type,
  [1431] = 5,
    ACTIONS(189), 1,
      sym_ident,
    ACTIONS(191), 1,
      anon_sym_LBRACK,
    ACTIONS(193), 1,
      anon_sym_fn,
    STATE(51), 1,
      sym_type,
    STATE(50), 2,
      sym_array_type,
      sym_fn_type,
  [1448] = 5,
    ACTIONS(189), 1,
      sym_ident,
    ACTIONS(191), 1,
      anon_sym_LBRACK,
    ACTIONS(193), 1,
      anon_sym_fn,
    STATE(100), 1,
      sym_type,
    STATE(50), 2,
      sym_array_type,
      sym_fn_type,
  [1465] = 5,
    ACTIONS(189), 1,
      sym_ident,
    ACTIONS(191), 1,
      anon_sym_LBRACK,
    ACTIONS(193), 1,
      anon_sym_fn,
    STATE(92), 1,
      sym_type,
    STATE(50), 2,
      sym_array_type,
      sym_fn_type,
  [1482] = 5,
    ACTIONS(189), 1,
      sym_ident,
    ACTIONS(191), 1,
      anon_sym_LBRACK,
    ACTIONS(193), 1,
      anon_sym_fn,
    STATE(96), 1,
      sym_type,
    STATE(50), 2,
      sym_array_type,
      sym_fn_type,
  [1499] = 5,
    ACTIONS(189), 1,
      sym_ident,
    ACTIONS(191), 1,
      anon_sym_LBRACK,
    ACTIONS(193), 1,
      anon_sym_fn,
    STATE(105), 1,
      sym_type,
    STATE(50), 2,
      sym_array_type,
      sym_fn_type,
  [1516] = 5,
    ACTIONS(189), 1,
      sym_ident,
    ACTIONS(191), 1,
      anon_sym_LBRACK,
    ACTIONS(193), 1,
      anon_sym_fn,
    STATE(101), 1,
      sym_type,
    STATE(50), 2,
      sym_array_type,
      sym_fn_type,
  [1533] = 5,
    ACTIONS(189), 1,
      sym_ident,
    ACTIONS(191), 1,
      anon_sym_LBRACK,
    ACTIONS(193), 1,
      anon_sym_fn,
    STATE(94), 1,
      sym_type,
    STATE(50), 2,
      sym_array_type,
      sym_fn_type,
  [1550] = 5,
    ACTIONS(189), 1,
      sym_ident,
    ACTIONS(191), 1,
      anon_sym_LBRACK,
    ACTIONS(193), 1,
      anon_sym_fn,
    STATE(48), 1,
      sym_type,
    STATE(50), 2,
      sym_array_type,
      sym_fn_type,
  [1567] = 1,
    ACTIONS(139), 5,
      ts_builtin_sym_end,
      anon_sym_alias,
      anon_sym_extern,
      anon_sym_type,
      anon_sym_let,
  [1575] = 3,
    ACTIONS(210), 1,
      anon_sym_COMMA,
    STATE(66), 1,
      aux_sym_functioncall_repeat1,
    ACTIONS(161), 2,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1586] = 3,
    ACTIONS(215), 1,
      anon_sym_COMMA,
    STATE(67), 1,
      aux_sym_struct_def_repeat1,
    ACTIONS(213), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1597] = 3,
    ACTIONS(218), 1,
      anon_sym_RPAREN,
    ACTIONS(220), 1,
      anon_sym_COMMA,
    STATE(69), 1,
      aux_sym_struct_def_repeat1,
  [1607] = 3,
    ACTIONS(222), 1,
      anon_sym_RPAREN,
    ACTIONS(224), 1,
      anon_sym_COMMA,
    STATE(67), 1,
      aux_sym_struct_def_repeat1,
  [1617] = 3,
    ACTIONS(171), 1,
      anon_sym_RBRACE,
    ACTIONS(226), 1,
      anon_sym_SEMI,
    STATE(70), 1,
      aux_sym_block_repeat1,
  [1627] = 3,
    ACTIONS(169), 1,
      anon_sym_LBRACE,
    ACTIONS(229), 1,
      anon_sym_COLON,
    STATE(20), 1,
      sym_block,
  [1637] = 3,
    ACTIONS(35), 1,
      anon_sym_RBRACE,
    ACTIONS(231), 1,
      anon_sym_SEMI,
    STATE(70), 1,
      aux_sym_block_repeat1,
  [1647] = 3,
    ACTIONS(233), 1,
      anon_sym_RBRACK,
    ACTIONS(235), 1,
      anon_sym_COMMA,
    STATE(73), 1,
      aux_sym_enum_def_repeat1,
  [1657] = 1,
    ACTIONS(238), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1663] = 3,
    ACTIONS(240), 1,
      sym_ident,
    ACTIONS(242), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      sym_annotated_ident,
  [1673] = 1,
    ACTIONS(213), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1679] = 3,
    ACTIONS(240), 1,
      sym_ident,
    ACTIONS(244), 1,
      anon_sym_RBRACE,
    STATE(76), 1,
      sym_annotated_ident,
  [1689] = 3,
    ACTIONS(169), 1,
      anon_sym_LBRACE,
    ACTIONS(246), 1,
      anon_sym_COLON,
    STATE(37), 1,
      sym_block,
  [1699] = 3,
    ACTIONS(248), 1,
      anon_sym_RBRACK,
    ACTIONS(250), 1,
      anon_sym_COMMA,
    STATE(86), 1,
      aux_sym_enum_def_repeat1,
  [1709] = 3,
    ACTIONS(169), 1,
      anon_sym_LBRACE,
    ACTIONS(252), 1,
      anon_sym_COLON,
    STATE(29), 1,
      sym_block,
  [1719] = 3,
    ACTIONS(37), 1,
      anon_sym_RPAREN,
    ACTIONS(254), 1,
      anon_sym_COMMA,
    STATE(66), 1,
      aux_sym_functioncall_repeat1,
  [1729] = 3,
    ACTIONS(33), 1,
      anon_sym_RBRACK,
    ACTIONS(256), 1,
      anon_sym_COMMA,
    STATE(66), 1,
      aux_sym_functioncall_repeat1,
  [1739] = 3,
    ACTIONS(258), 1,
      anon_sym_COMMA,
    ACTIONS(260), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_struct_def_repeat1,
  [1749] = 3,
    ACTIONS(262), 1,
      anon_sym_COMMA,
    ACTIONS(264), 1,
      anon_sym_RBRACE,
    STATE(83), 1,
      aux_sym_struct_def_repeat1,
  [1759] = 3,
    ACTIONS(240), 1,
      sym_ident,
    ACTIONS(260), 1,
      anon_sym_RBRACE,
    STATE(76), 1,
      sym_annotated_ident,
  [1769] = 3,
    ACTIONS(266), 1,
      anon_sym_RBRACK,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    STATE(73), 1,
      aux_sym_enum_def_repeat1,
  [1779] = 3,
    ACTIONS(240), 1,
      sym_ident,
    ACTIONS(270), 1,
      anon_sym_RPAREN,
    STATE(68), 1,
      sym_annotated_ident,
  [1789] = 3,
    ACTIONS(169), 1,
      anon_sym_LBRACE,
    ACTIONS(272), 1,
      anon_sym_COLON,
    STATE(26), 1,
      sym_block,
  [1799] = 3,
    ACTIONS(222), 1,
      anon_sym_RPAREN,
    ACTIONS(240), 1,
      sym_ident,
    STATE(76), 1,
      sym_annotated_ident,
  [1809] = 2,
    ACTIONS(240), 1,
      sym_ident,
    STATE(76), 1,
      sym_annotated_ident,
  [1816] = 2,
    ACTIONS(266), 1,
      anon_sym_RBRACK,
    ACTIONS(274), 1,
      sym_ident,
  [1823] = 2,
    ACTIONS(169), 1,
      anon_sym_LBRACE,
    STATE(22), 1,
      sym_block,
  [1830] = 2,
    ACTIONS(169), 1,
      anon_sym_LBRACE,
    STATE(30), 1,
      sym_block,
  [1837] = 2,
    ACTIONS(169), 1,
      anon_sym_LBRACE,
    STATE(28), 1,
      sym_block,
  [1844] = 2,
    ACTIONS(274), 1,
      sym_ident,
    ACTIONS(276), 1,
      anon_sym_RBRACK,
  [1851] = 2,
    ACTIONS(169), 1,
      anon_sym_LBRACE,
    STATE(20), 1,
      sym_block,
  [1858] = 2,
    ACTIONS(278), 1,
      anon_sym_LBRACK,
    ACTIONS(280), 1,
      anon_sym_LBRACE,
  [1865] = 2,
    ACTIONS(240), 1,
      sym_ident,
    STATE(84), 1,
      sym_annotated_ident,
  [1872] = 1,
    ACTIONS(233), 2,
      anon_sym_RBRACK,
      anon_sym_COMMA,
  [1877] = 2,
    ACTIONS(169), 1,
      anon_sym_LBRACE,
    STATE(37), 1,
      sym_block,
  [1884] = 1,
    ACTIONS(282), 1,
      anon_sym_SEMI,
  [1888] = 1,
    ACTIONS(284), 1,
      anon_sym_EQ,
  [1892] = 1,
    ACTIONS(286), 1,
      anon_sym_COLON,
  [1896] = 1,
    ACTIONS(288), 1,
      anon_sym_SEMI,
  [1900] = 1,
    ACTIONS(290), 1,
      anon_sym_RBRACK,
  [1904] = 1,
    ACTIONS(292), 1,
      anon_sym_LPAREN,
  [1908] = 1,
    ACTIONS(294), 1,
      anon_sym_else,
  [1912] = 1,
    ACTIONS(296), 1,
      sym_ident,
  [1916] = 1,
    ACTIONS(298), 1,
      sym_ident,
  [1920] = 1,
    ACTIONS(300), 1,
      anon_sym_SEMI,
  [1924] = 1,
    ACTIONS(302), 1,
      anon_sym_SEMI,
  [1928] = 1,
    ACTIONS(304), 1,
      anon_sym_LPAREN,
  [1932] = 1,
    ACTIONS(306), 1,
      anon_sym_SEMI,
  [1936] = 1,
    ACTIONS(308), 1,
      anon_sym_EQ,
  [1940] = 1,
    ACTIONS(310), 1,
      anon_sym_SEMI,
  [1944] = 1,
    ACTIONS(312), 1,
      anon_sym_COLON,
  [1948] = 1,
    ACTIONS(274), 1,
      sym_ident,
  [1952] = 1,
    ACTIONS(314), 1,
      anon_sym_COLON,
  [1956] = 1,
    ACTIONS(316), 1,
      anon_sym_EQ,
  [1960] = 1,
    ACTIONS(318), 1,
      anon_sym_SEMI,
  [1964] = 1,
    ACTIONS(320), 1,
      anon_sym_SEMI,
  [1968] = 1,
    ACTIONS(322), 1,
      anon_sym_SEMI,
  [1972] = 1,
    ACTIONS(324), 1,
      anon_sym_SEMI,
  [1976] = 1,
    ACTIONS(326), 1,
      anon_sym_SEMI,
  [1980] = 1,
    ACTIONS(328), 1,
      ts_builtin_sym_end,
  [1984] = 1,
    ACTIONS(330), 1,
      sym_ident,
  [1988] = 1,
    ACTIONS(332), 1,
      sym_ident,
  [1992] = 1,
    ACTIONS(334), 1,
      anon_sym_COLON,
  [1996] = 1,
    ACTIONS(336), 1,
      sym_ident,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 42,
  [SMALL_STATE(4)] = 84,
  [SMALL_STATE(5)] = 126,
  [SMALL_STATE(6)] = 168,
  [SMALL_STATE(7)] = 210,
  [SMALL_STATE(8)] = 252,
  [SMALL_STATE(9)] = 294,
  [SMALL_STATE(10)] = 336,
  [SMALL_STATE(11)] = 375,
  [SMALL_STATE(12)] = 414,
  [SMALL_STATE(13)] = 453,
  [SMALL_STATE(14)] = 492,
  [SMALL_STATE(15)] = 531,
  [SMALL_STATE(16)] = 570,
  [SMALL_STATE(17)] = 592,
  [SMALL_STATE(18)] = 614,
  [SMALL_STATE(19)] = 636,
  [SMALL_STATE(20)] = 660,
  [SMALL_STATE(21)] = 681,
  [SMALL_STATE(22)] = 702,
  [SMALL_STATE(23)] = 723,
  [SMALL_STATE(24)] = 744,
  [SMALL_STATE(25)] = 765,
  [SMALL_STATE(26)] = 786,
  [SMALL_STATE(27)] = 807,
  [SMALL_STATE(28)] = 828,
  [SMALL_STATE(29)] = 849,
  [SMALL_STATE(30)] = 870,
  [SMALL_STATE(31)] = 891,
  [SMALL_STATE(32)] = 912,
  [SMALL_STATE(33)] = 933,
  [SMALL_STATE(34)] = 954,
  [SMALL_STATE(35)] = 975,
  [SMALL_STATE(36)] = 998,
  [SMALL_STATE(37)] = 1019,
  [SMALL_STATE(38)] = 1040,
  [SMALL_STATE(39)] = 1061,
  [SMALL_STATE(40)] = 1082,
  [SMALL_STATE(41)] = 1114,
  [SMALL_STATE(42)] = 1138,
  [SMALL_STATE(43)] = 1162,
  [SMALL_STATE(44)] = 1182,
  [SMALL_STATE(45)] = 1214,
  [SMALL_STATE(46)] = 1238,
  [SMALL_STATE(47)] = 1259,
  [SMALL_STATE(48)] = 1278,
  [SMALL_STATE(49)] = 1292,
  [SMALL_STATE(50)] = 1306,
  [SMALL_STATE(51)] = 1320,
  [SMALL_STATE(52)] = 1334,
  [SMALL_STATE(53)] = 1355,
  [SMALL_STATE(54)] = 1376,
  [SMALL_STATE(55)] = 1397,
  [SMALL_STATE(56)] = 1414,
  [SMALL_STATE(57)] = 1431,
  [SMALL_STATE(58)] = 1448,
  [SMALL_STATE(59)] = 1465,
  [SMALL_STATE(60)] = 1482,
  [SMALL_STATE(61)] = 1499,
  [SMALL_STATE(62)] = 1516,
  [SMALL_STATE(63)] = 1533,
  [SMALL_STATE(64)] = 1550,
  [SMALL_STATE(65)] = 1567,
  [SMALL_STATE(66)] = 1575,
  [SMALL_STATE(67)] = 1586,
  [SMALL_STATE(68)] = 1597,
  [SMALL_STATE(69)] = 1607,
  [SMALL_STATE(70)] = 1617,
  [SMALL_STATE(71)] = 1627,
  [SMALL_STATE(72)] = 1637,
  [SMALL_STATE(73)] = 1647,
  [SMALL_STATE(74)] = 1657,
  [SMALL_STATE(75)] = 1663,
  [SMALL_STATE(76)] = 1673,
  [SMALL_STATE(77)] = 1679,
  [SMALL_STATE(78)] = 1689,
  [SMALL_STATE(79)] = 1699,
  [SMALL_STATE(80)] = 1709,
  [SMALL_STATE(81)] = 1719,
  [SMALL_STATE(82)] = 1729,
  [SMALL_STATE(83)] = 1739,
  [SMALL_STATE(84)] = 1749,
  [SMALL_STATE(85)] = 1759,
  [SMALL_STATE(86)] = 1769,
  [SMALL_STATE(87)] = 1779,
  [SMALL_STATE(88)] = 1789,
  [SMALL_STATE(89)] = 1799,
  [SMALL_STATE(90)] = 1809,
  [SMALL_STATE(91)] = 1816,
  [SMALL_STATE(92)] = 1823,
  [SMALL_STATE(93)] = 1830,
  [SMALL_STATE(94)] = 1837,
  [SMALL_STATE(95)] = 1844,
  [SMALL_STATE(96)] = 1851,
  [SMALL_STATE(97)] = 1858,
  [SMALL_STATE(98)] = 1865,
  [SMALL_STATE(99)] = 1872,
  [SMALL_STATE(100)] = 1877,
  [SMALL_STATE(101)] = 1884,
  [SMALL_STATE(102)] = 1888,
  [SMALL_STATE(103)] = 1892,
  [SMALL_STATE(104)] = 1896,
  [SMALL_STATE(105)] = 1900,
  [SMALL_STATE(106)] = 1904,
  [SMALL_STATE(107)] = 1908,
  [SMALL_STATE(108)] = 1912,
  [SMALL_STATE(109)] = 1916,
  [SMALL_STATE(110)] = 1920,
  [SMALL_STATE(111)] = 1924,
  [SMALL_STATE(112)] = 1928,
  [SMALL_STATE(113)] = 1932,
  [SMALL_STATE(114)] = 1936,
  [SMALL_STATE(115)] = 1940,
  [SMALL_STATE(116)] = 1944,
  [SMALL_STATE(117)] = 1948,
  [SMALL_STATE(118)] = 1952,
  [SMALL_STATE(119)] = 1956,
  [SMALL_STATE(120)] = 1960,
  [SMALL_STATE(121)] = 1964,
  [SMALL_STATE(122)] = 1968,
  [SMALL_STATE(123)] = 1972,
  [SMALL_STATE(124)] = 1976,
  [SMALL_STATE(125)] = 1980,
  [SMALL_STATE(126)] = 1984,
  [SMALL_STATE(127)] = 1988,
  [SMALL_STATE(128)] = 1992,
  [SMALL_STATE(129)] = 1996,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(126),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 5, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 5, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 4, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 7, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 7, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_functioncall, 6, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_functioncall, 6, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 9, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 9, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_functioncall, 4, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_functioncall, 4, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_functioncall, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_functioncall, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 5, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 5, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_op, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_op, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 8, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 8, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 4, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 4, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ifelse, 5, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ifelse, 5, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 4, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let, 4, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 5, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 5, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 6, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 6, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_functioncall, 5, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_functioncall, 5, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [141] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(108),
  [144] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(129),
  [147] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(127),
  [150] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(126),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_functioncall_repeat1, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_type, 5, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn_type, 5, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_type, 3, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_type, 3, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 1, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_type, 6, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn_type, 6, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [199] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fn_type_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [202] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fn_type_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [205] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fn_type_repeat1, 2, 0, 0), SHIFT_REPEAT(112),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fn_type_repeat1, 2, 0, 0),
  [210] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_functioncall_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_def_repeat1, 2, 0, 0),
  [215] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_def_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [226] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_def_repeat1, 2, 0, 0),
  [235] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_def_repeat1, 2, 0, 0), SHIFT_REPEAT(117),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotated_ident, 3, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_def, 4, 0, 0),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_def, 6, 0, 1),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_def, 7, 0, 1),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias, 4, 0, 1),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_def, 6, 0, 1),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [310] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_def, 8, 0, 1),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [318] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_def, 1, 0, 0),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_def, 7, 0, 1),
  [322] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 1, 0, 0),
  [324] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_def, 8, 0, 1),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [328] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_citrus(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
